---
- name: Install libpcsclite dependency
  become: true
  ansible.builtin.package:
    name: "{{ _acme_proxy_pcsc_packages[ansible_os_family] }}"
    state: present
  when:
    - acme_proxy_install_pcsc
    - ansible_os_family in _acme_proxy_pcsc_packages
