---
- name: Deploy systemd unit
  become: true
  ansible.builtin.template:
    src: acme-proxy.service.j2
    dest: /etc/systemd/system/acme-proxy.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload systemd daemon
    - restart acme-proxy

- name: Enable and manage acme-proxy service
  become: true
  ansible.builtin.systemd:
    name: acme-proxy
    enabled: "{{ acme_proxy_service_enabled }}"
    state: "{{ acme_proxy_service_state }}"
    daemon_reload: true
